name: Take Screenshots

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install puppeteer
      - name: Take screenshot
        run: |
          node scripts/screenshot.js
      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png
